version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: projet_AWI
    restart: unless-stopped
    environment:
      POSTGRES_USER: secureapp
      POSTGRES_PASSWORD: secureapp
      POSTGRES_DB: secureapp
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: projet_AWI_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
