version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: projet_AWI_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: secureapp
      POSTGRES_PASSWORD: secureapp
      POSTGRES_DB: secureapp
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d
      - db_data_dev:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    networks:
      - secure_net_dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: projet_AWI_backend_dev
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://secureapp:secureapp@db:5432/secureapp
      JWT_SECRET: "mon_secret_jwt_super_long_et_complexe"
      JWT_EXPIRATION: "15m"
      REFRESH_EXPIRATION: "7d"
    volumes:
      - ./backend/certs:/app/certs:ro
    ports:
      - "4000:4000"
    networks:
      - secure_net_dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: projet_AWI_frontend_dev
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - secure_net_dev

  adminer:
    image: adminer:latest
    container_name: projet_AWI_adminer_dev
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - secure_net_dev

volumes:
  db_data_dev:

networks:
  secure_net_dev:
